version: '3'

services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_DB: app
      MYSQL_PASSWORD: ChangeMe
      MYSQL_USER: symfony
    volumes:
      - db-data:/var/lib/mysql/data:rw
  
  app:
    image: my-personal-db:latest
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://symfony:ChangeMe@database:3306/app

volumes:
  db-data:



  
  